name: Build

on:
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn type-check

      - name: Prettier
        run: yarn prettier src/ --check

      - name: Build
        uses: ./.github/actions/build