name: Build & Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn type-check

      - name: Prettier
        run: yarn prettier src/ --check

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Upload artifact
        id: upload-dist-artifact
        uses: actions/upload-artifact@v4
        with:
          name: localstack-ses-viewer-dist
          path: dist/
          retention-days: 30
          if-no-files-found: error